// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIhx4W5LVwiaLOidRY1NvxOGKdHtP27jk',
    appId: '1:600109046463:web:5ec8a96658f029f236840a',
    messagingSenderId: '600109046463',
    projectId: 'blood-donation-app-8b965',
    authDomain: 'blood-donation-app-8b965.firebaseapp.com',
    storageBucket: 'blood-donation-app-8b965.appspot.com',
    measurementId: 'G-XEFQYBLKD3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGnI2gtizfcYsyLOOEl30Kamnn_8ZcgSo',
    appId: '1:600109046463:android:0e4a7888aea0867436840a',
    messagingSenderId: '600109046463',
    projectId: 'blood-donation-app-8b965',
    storageBucket: 'blood-donation-app-8b965.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkXMFWpI47HFxOkc0zEsddZ8jT4-7xR8o',
    appId: '1:600109046463:ios:c6eec1a2b7ae7de136840a',
    messagingSenderId: '600109046463',
    projectId: 'blood-donation-app-8b965',
    storageBucket: 'blood-donation-app-8b965.appspot.com',
    iosBundleId: 'com.example.newproject9',
  );
}
